#!/bin/sh

KEYGRIP_FILE="/home/"$PAM_USER"/.gnupg/pam_exec-gpg"

if [ "$(id -un)" != "$PAM_USER" ]; then
    su "$PAM_USER" -s "$0" "$@"
else
    read -r PAM_PASS

    if [ -f "$KEYGRIP_FILE" ]; then
        while read line; do
            printf "%s" "$PAM_PASS" | /usr/lib/gnupg/gpg-preset-passphrase --passphrase "$(cat)" --preset "$line"
        done < "$KEYGRIP_FILE"
    fi
fi

exit 0
