#!/bin/sh

agent_preset_passphrase () {
    /usr/lib/gnupg/gpg-preset-passphrase --preset "$1" <<EOF
$2
EOF

}

read -r PAM_PASS

if [ -f /home/"$PAM_USER"/.gnupg/pam_exec-gpg ]; then
        agent_preset_passphrase "$(cat /home/"$PAM_USER"/.gnupg/pam_exec-gpg)" "$PAM_PASS" &
fi

exit 0
